name: Deploy Terraform using OIDC and Managed Identity

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'it is infra deployment'
        required: true
        default: 'dev'
        type: string
         
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: terraform deploy
    runs-on: windows-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4

      - name: Azure Login using fedreat credentials (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MYSECRETINFRA }}
          tenant-id: ${{ secrets.MYTENANT }}
          subscription-id: ${{ secrets.MYSUBSCRIPTION }}
          auth-type: 'service-principal'
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4
      - name: create terraform.tfvars from secrets 
        run: |
          echo "${{ secrets.MYTERRAFORMTFVARS }}" > terraform.tfvars
          working_directory = tf-landing-zone-code\Terraformfolder\environment\dev
      - name: add subscription id on provider.tf
        run: |
          echo 'provider "azurerm" {
            features {}
            subscription_id = "${{ secrets.MYSUBSCRIPTION }}"
          }' > provider.tf
          working_directory = tf-landing-zone-code\Terraformfolder\environment\dev

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6  # Apna version yahan daalein
            
      - name: Terraform Init
        run: terraform init
        working-directory: tf-landing-zone-code/Terraformfolder/environment/dev
        shell: pwsh

      - name: Terraform validate 
        run: |
          terraform fmt -check=true
          terraform validate
          working-directory = tf-landing-zone-code\Terraformfolder\environment\dev
      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false -no-color -var-file=terraform.tfvars
        working-directory: tf-landing-zone-code/Terraformfolder/environment/dev
       
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: tf-landing-zone-code/Terraformfolder/environment/dev